example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
from django.urls import pathfrom katalog.views import show_catalogapp_name = 'katalog'urlpatterns = [    path('', show_catalog, name='show_catalog'),]

mywatchlist/urls.py
from django.urls import pathfrom mywatchlist.views import show_watchlistfrom mywatchlist.views import show_xmlfrom mywatchlist.views import show_xml_by_idfrom mywatchlist.views import show_jsonfrom mywatchlist.views import show_json_by_idfrom mywatchlist.views import show_htmlapp_name = 'MyWatchList'urlpatterns = [    path('', show_watchlist, name='show_watchlist'),    path('xml/', show_xml, name='show_xml'),    path('json/', show_json, name='show_json'),    path('html/', show_html, name='show_html'),    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

todolist/urls.py
from django.urls import path
from todolist.views import register
from todolist.views import login_user
from todolist.views import show_todolist
from todolist.views import logout_user
from todolist.views import create_task
from todolist.views import status
from todolist.views import delete
from todolist.views import show_json
from todolist.views import add_todo


app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', create_task, name='create-task'),
    path('status/<int:id>', status, name='status'),
    path('delete/<int:id>', delete, name='delete'),
    path('json/', show_json, name='show_json'),
    path('add/',add_todo, name='add_todo'),
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

class MyWatchListItem(models.Model):
    watched = models.BooleanField()
    title = models.CharField(max_length=255)
    rating = models.IntegerField()
    release_date = models.CharField(max_length=255)
    review = models.TextField()

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    title = models.CharField(max_length=255)
    description = models.TextField()
    

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem

# TODO: Create your views here.
def show_catalog(request):
    data_katalog = CatalogItem.objects.all()
    context = {
        'list_katalog': data_katalog,
        'nama': 'Soraya Sabrina',
        'npm': '2106651061',
    }
    return render(request, "katalog.html", context)

mywatchlist/views.py
from django.shortcuts import render
from mywatchlist.models import MyWatchListItem
from django.http import HttpResponse
from django.core import serializers

# TODO: Create your views here.
def show_watchlist(request):
    return render(request, "mywatchlist.html", context)

data_tontonan = MyWatchListItem.objects.all()
context = {
    'list_tontonan': data_tontonan,
    'nama': 'Soraya Sabrina',
    'npm': '2106651061',
}

def show_xml(request):
    data = MyWatchListItem.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = MyWatchListItem.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

data_tontonan = MyWatchListItem.objects.all()
contextHTML = {
        'list_tontonan': data_tontonan
    }

def show_html(request):
    return render(request, 'watchedlist.html', contextHTML)

def show_xml_by_id(request, id):
    data = MyWatchListItem.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = MyWatchListItem.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

todolist/views.py
import datetime
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from todolist.models import Task
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.http import HttpResponseRedirect
from django import forms
from django.http import HttpResponse
from django.core import serializers
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

data_todo = Task.objects.all()
context = {
    'list_todo': data_todo,
    'nama': 'Soraya Sabrina',
    'npm': '2106651061',
}
@login_required(login_url='/todolist/login/')
def show_todolist(request):
    return render(request, "todolist.html", context)

def show_json(request):
    todo = Task.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", todo), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('todolist:show_todolist')
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return redirect('todolist:login')

class TaskForm(forms.Form):
    title = forms.CharField(max_length=255)
    description = forms.CharField(widget=forms.Textarea)

@login_required(login_url='/todolist/login/')
def create_task(request):
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            Task.objects.create(title=form.cleaned_data["title"], description=form.cleaned_data["description"], date=datetime.datetime.now(), user=request.user)
            return HttpResponseRedirect(reverse('todolist:show_todolist'))
    else:
        form = TaskForm()
    
    context = {'form':form}
    return render(request, 'create-task.html', context)

@login_required(login_url='/todolist/login/')
def status(request, id):
    todo = Task.objects.get(id=id, user=request.user)
    todo.is_finished = not todo.is_finished
    todo.save(update_fields=['is_finished'])
    return HttpResponseRedirect(reverse('todolist:show_todolist'))

@login_required(login_url='/todolist/login/')
def delete(request, id):
    Task.objects.get(id=id).delete()
    return redirect('todolist:show_todolist')

@csrf_exempt
def add_todo(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        todo = Task.objects.create(title=title, description=description,date=datetime.date.today(), user=request.user)
        return JsonResponse({'pk':todo.pk,
                'fields':{
                'title':todo.title,
                'date':todo.date,
                'description':todo.description,
            }})

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{npm}}</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for katalog in list_katalog %}
    <tr>
      <th>{{katalog.item_name}}</th>
      <th>{{katalog.item_price}}</th>
      <th>{{katalog.item_stock}}</th>
      <th>{{katalog.rating}}</th>
      <th>{{katalog.description}}</th>
      <th>{{katalog.item_url}}</th>
  </tr>
  {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Tugas 3 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{npm}}</p>

  <table>
    <tr>
      <th>Watched</th>
      <th>Title</th>
      <th>Rating</th>
      <th>Release Date</th>
      <th>Review</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for watchlist in data_tontonan %}
    <tr>
      <th>{{watchlist.watched}}</th>
      <th>{{watchlist.title}}</th>
      <th>{{watchlist.rating}}</th>
      <th>{{watchlist.release_date}}</th>
      <th>{{watchlist.review}}</th>
  </tr>
  {% endfor %}
  </table>
  <button><a href="{% url 'wishlist:logout' %}">Logout</a></button>

 {% endblock content %}

mywatchlist/templates/watchedlist.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Tugas 3 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{npm}}</p>

  <table>
    <tr>
      <th>Watched</th>
      <th>Title</th>
      <th>Rating</th>
      <th>Release Date</th>
      <th>Review</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for watchlist in list_tontonan %}
    <tr>
      <th>{{watchlist.watched}}</th>
      <th>{{watchlist.title}}</th>
      <th>{{watchlist.rating}}</th>
      <th>{{watchlist.release_date}}</th>
      <th>{{watchlist.review}}</th>
  </tr>
  {% endfor %}
  </table>

 {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

todolist/templates/create-task.html
{% extends 'base.html' %}
{% load static %}

{% block content %}  
<link rel="stylesheet" href="{% static 'todolist/create-task.css' %}">

<h1>Add New Task</h1>

        <form method="POST">  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Create"/></td>  
                </tr>  
            </table>  
        </form>

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Login</title>
<link rel="stylesheet" href="{% static 'todolist/login.css' %}">
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td class="form">Username</td>
            </tr><tr>
                <td><input type="text" name="username" placeholder="Enter Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td class="form">Password</td>
            </tr><tr>
                <td><input type="password" name="password" placeholder="Enter Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    <b>Belum mempunyai akun?</b> <a href="{% url 'todolist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Registrasi Akun</title>
<link rel="stylesheet" href="{% static 'todolist/register.css' %}">
{% endblock meta %}

{% block content %}  
<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table border="0">  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}
{% load static %}

 {% block content %}
 <link rel="stylesheet" href="{% static 'todolist/todolist.css' %}">

  {% if user.is_authenticated %}
    <br>
    <h1 style="font-size:2vw;text-align:center;font-family:sans-serif;color: white;"> Welcome, {{ user.get_username }}! </h1>
    <p style="font-style: italic;text-align:center;font-family: sans-serif;color: white;">  your to do list: </p>
    <form id="task-form" method="POST" action="/todolist/add/" onsubmit="return false;"></form>

    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <script>
            $(document).ready(() => {
                const card = (todo) => `<div class="card">
                    <p style="font-size:13px;">${todo.fields.date} - ${todo.fields.is_finished ? 'Finished' : 'Unfinished'}</p>
                    <p style="text-align:center;font-size:20px;">${todo.fields.title}</p>
                    <p style="text-align:center;font-size:15px;">${todo.fields.description}</p>              
                    </div>`
                                    
                const addTask = (todo) => {
                    return $('.outer').append(card(todo))
                }   
            
                $.get('/todolist/json/', function(todo) {
                    todo.map((task) => {
                        addTask(task)
                    })
                })
    
                $(`#add-task`).click(function(){
                    if ($('#title').val() && $('#description').val()){
                        $.post('/todolist/add/', {
                                title: $('#title').val(),
                                description: $('#description').val(),
                            },
                            function(res, status){
                                if(status == 'success'){
                                    addTask(res)
                                    $('#title').val('')
                                    $('#description').val('')
                                }
                            }
                        )
                        return false
                    }
                })
            })
        
        </script>
       </head>
    
    <table border = "1" width = 413 style="margin-left:auto;margin-right:auto">
        <tr>
        <th>Date Added</th>
        <th>Title</th>
        <th>Description</th>
        <th>Status</th>
        <th>Options</th>
        </tr>
        {% comment %} Add the data below this line {% endcomment %}
        {% for todolist in list_todo %}
            <tr>
                <td>{{todolist.date}}</td>
                <td>{{todolist.title}}</td>
                <td>{{todolist.description}}</td>

                {% if todolist.is_finished %}
                    <td>Selesai</td>
                {% else %}
                    <td>Belum selesai</td>
                {% endif %}

                <td>
                    <button style="margin-left:auto;margin-right:auto;display:block;margin-top:0%;margin-bottom:0%"><a href="{% url 'todolist:status' todolist.id %}">Status</a></button>
                    <button style="margin-left:auto;margin-right:auto;display:block;margin-top:0%;margin-bottom:0%"><a href="{% url 'todolist:delete' todolist.id %}">Delete</a></button>
                </td>
            </tr>
        {% endfor %}
    </table>

    
    <div class="card">
        {% for todolist in list_todo %}
        <h4 class="card-title">{{todolist.title}}</h4>
        <h5 class="card-date">{{todolist.date}}</h5>
        <p class="card-desc">{{todolist.description}}</p>
        {% if todolist.is_finished %}
        <status>
                    <td style="font-family: Arial Rounded MT Bold;font-weight: 30;font-size: small">Selesai</td>
                {% else %}
                    <td style="font-family: Arial Rounded MT Bold;font-weight: 30;font-size: small">Belum selesai</td>
                {% endif %}
        {% endfor %}
        </status>
    </div> 

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">New Task</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="POST">
                    {% csrf_token %}
                    <table>
                        <tr>
                            <td>Title</td>
                            <td><input type="text" name="title" class="form-control" id="title"></td>
                        </tr>
                                
                        <tr>
                            <div>
                                <td>Description</td>
                                <td><input type="text" name="description" class="form-control" id="description"></td>
                            </div>
                        </tr>
                    </table>
                </form>
            </div>
        </div>
    </div>

    <br>
    <br>
    <br>
    <button style="margin-left:auto;margin-right:auto;display:block;margin-top:0%;margin-bottom:0%"><a href="{% url 'todolist:create-task' %}">Add New Task</a></button>
    <br>
    <button style="margin-left:auto;margin-right:auto;display:block;margin-top:0%;margin-bottom:0%"><a href="{% url 'todolist:logout' %}">Logout</a></button>
    <br>
    <button type="button" class="btn btn-outline-dark btn-sm" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Task</button>


    
  {% endif %}

 {% endblock content %}